language:
  - "python"
python:
  - "3.6"
  - "3.7"
services:
  - mysql
install:
  - pip install -r department-app/api/requirements.txt
  - pip install coveralls
before_install:
  - mysql -e "CREATE DATABASE deps_emps_db_test;"
script:
  - pylint --rcfile=.pylintrc department-app/api
after_success:
  - coveralls
