language: 
  - python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install pylint-flask-sqlalchemy
  - pip install coveralls 
script:
  - pylint --rcfile=.pylintrc department-app
  - bash scripts/test_start.sh
after_success: 
  - coveralls