language: 
  - python
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - mysql
install:
  - pip install -r requirements.txt
  - pip install coveralls 
before_script:
  - mysql -e "CREATE DATABASE deps_emps_db_test;"
script:
  - pylint --rcfile=.pylintrc department-app
  - bash scripts/test_start_travis.sh
after_success: 
  - coveralls