language: 
  - python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - python department-app/setup.py install
  - pip install pylint
  - pip install pylint-flask-sqlalchemy
  - pip install coveralls 
script:
  - pylint --output-format=text --load-plugins pylint_flask_sqlalchemy department-app
after_success: 
  - coveralls